module.exports =
[
    'src/polyfills/*.js',
    'libs/es6-promise/es6-promise.js',
    'src/utils/*.js',
    'src/core/*.js',
    'src/debugging/*.js',
    'src/application/GameOptions.js',
    'src/actor-components/*.js',
    'src/actors/*.js',
    'src/events/*.js',
    'src/logic/*.js',
    'src/processes/*.js',
    'src/resources/WorkerResourceManager.js',
    'src/scripting/*.js',
    'src/views/*.js',
    'src/worker/*.js',
    'src/worker-messages/*.js',
    'src/Worker.js'
];